### ISSUE TITLE
3.6.3-b2 点击下载客户端助手，页面404

### ISSUE THREAD

**Issue by siruoren** [eomsoft/teleport#288]
提示“助手：未连接”，弹出的窗口提出下载windows或macos，点击页面404

**Comment by wntd888** [comment]
同问，助手安装文件应该放到哪个目录下才能下载呢？

**Comment by siruoren** [comment]
> 

![image](https://user-images.githubusercontent.com/28772488/188081614-c35b1e7a-e9ca-44a9-809d-60a6870b0492.png)

![image](https://user-images.githubusercontent.com/28772488/188081691-59707e8c-f1c3-4d44-872f-d24c9bb40763.png)
