### ISSUE TITLE
任意用户登录高危漏洞0day

### ISSUE THREAD

**Issue by wuqigang110** [eomsoft/teleport#289]
teleport堡垒机登录接口存在逻辑漏洞可以绕过登录验证，导致可任意账号登入系统。
漏洞文件：service/www/teleport/webroot/app/controller/auth.py 在user.login 函数中如果password为None则不进行密码校验，在登录的json字符串中不传入password会导致获取到的参数为None，可以跳过密码验证直接登录成功。
影响产品名称：teleport堡垒机
影响产品版本：3.6.3beta2及之前版本
危害：攻击者可以利用该漏洞登录堡垒机后台。

**Comment by apexliu** [comment]
已发布对应安全漏洞修复补丁，针对目前使用最广泛的几个版本进行修复，如果你目前使用的版本不在此列，请尽快升级到最接近的版本，并应用相应的补丁：
3.2.2
3.5.6-rc6
3.6.3-b2

**Comment by wuqigang110** [comment]
作者辛苦，凌晨都在写代码，需要的尽快升级
补丁包下载：https://tp4a.com/download
![111](https://user-images.githubusercontent.com/111330501/185022992-fb191818-399b-444c-bbe3-7363e4eb8bb4.jpg)
