### ISSUE TITLE
可否开发mac版客户端工具

### ISSUE THREAD

**Issue by flybirdsxxx** [eomsoft/teleport#35]
功能很不错，也没有什么问题，可否增加mac客户端电脑访问支持？

**Comment by apexliu** [comment]
有这个计划，只是目前因为别的更重要的功能，将这块向后延期了。

**Comment by SweetHammer** [comment]
我们公司也是，开发用mac的人不少，如果有mac版的teleport助手能支持 iterm2，就更完美了

**Comment by longfengfirst** [comment]
我公司比较特别，开发用的ubuntu和mac，windows的反而没有。

**Comment by apexliu** [comment]
再等等，会有的。  :)

**Comment by flapjackegg** [comment]
同样期待中，支持 teleport！

**Comment by apexliu** [comment]
谢谢支持！Mac版助手已经开发了，不过目前仅支持SSH（支持系统自带terminal和iterm2），新版本会附带Mac助手，敬请期待...

**Comment by apexliu** [comment]
v3技术预览版已经有了Mac版助手了，可以试试。

**Comment by apexliu** [comment]
v3.0.1.6-beta版已经同步更新了新的Mac助手。
