### ISSUE TITLE
建议初始密码初次登录后强制要求更改密码

### ISSUE THREAD

**Issue by ltyely** [eomsoft/teleport#37]
建议初始密码初次登录后强制要求更改密码，这样在实际管理中，避免出现普通用户不负责任，不修改密码被其他人利用的情况。

**Comment by apexliu** [comment]
开发中的新版本这块儿改为由系统随机生成密码并发送到用户邮箱。

**Comment by ltyely** [comment]
如果强制要求发送到用户邮箱的话，对于内网用户、未部署mail服务的环境是不是不太友好？我就是因为这个原因放弃了jumpserver

**Comment by apexliu** [comment]
有道理！那就这样，对于无邮箱设定的用户，可由管理员重置密码为默认密码，用户登录时，如果为默认密码，则只能进行密码设置操作。用户设定密码后，重新登录系统，方可正常使用。

**Comment by apexliu** [comment]
从v3技术预览版开始，已经不再有默认密码的概念了，管理员可以重设密码，如果系统配置了SMTP服务，也可由用户自己重置密码。
