### ISSUE TITLE
mac版本助手问题

### ISSUE THREAD

**Issue by ChristopherQian** [eomsoft/teleport#47]
1.mac版升级了3.0.0.2版本后，助手显示升级成功但是在web页面上查看依然是3.0.0.1.
2.mac版升级3.0.0.2版本后，ssh连接报错“Invalid key length”

**Comment by apexliu** [comment]
问题1是bug，下一版会修正；
问题2，请查看wiki的已知问题，可以先临时解决。

**Comment by apexliu** [comment]
已修正。
