### ISSUE TITLE
运维人员功能不正常

### ISSUE THREAD

**Issue by jndhy1** [eomsoft/teleport#49]
运维人员不能打开授权的服务器，显示无法连接该设备，而admin管理员是可以的，我使用的是v3.0，不知是设置问题还是软件问题

**Comment by apexliu** [comment]
如果在运维人员的运维界面已经显示了被授权的远程服务器了，那么按设计是应该能连接的，如果不能，则是BUG，需要进一步调查。

**Comment by apexliu** [comment]
请下载最新的v3.0.0.4版本进行测试，建议先将运维策略全部删除，然后重新建立运维策略再试。如果还有问题，请留言。

**Comment by apexliu** [comment]
在v3.0.1.6-beta中重现了类似问题，原因在于在同一个授权策略中，直接添加了远程账号，又添加了此远程账号所在主机，导致后续处理时同一用户对同一远程账号出现重复，而后台在查询数据库时发现重复就报错，导致无法进行远程。

此问题在下一版发布时将得到修正。

**Comment by apexliu** [comment]
修正了此问题的v3.0.2.9版本已经发布。
