### ISSUE TITLE
在用户列表中更改用户

### ISSUE THREAD

**Issue by ouchao** [eomsoft/teleport#51]
在【用户列表】中编辑用户信息，修改用户项目后，在【运维】->【 运维授权】->【授权策略】中看到的用户还是旧的姓名。

**Comment by apexliu** [comment]
已重现，近期修改。

**Comment by apexliu** [comment]
已修改，参见 7bfbfc9a4d70917f0a1f0bc48c29f23e4497129e 和 1657622385713e52aa11e70c494eac19a92fa722
