### ISSUE TITLE
RDP连接禁止访问驱动器实际还是能访问驱动器。

### ISSUE THREAD

**Issue by triblewinn** [eomsoft/teleport#55]
管理员设置了禁止驱动器的映射。
实际上RDP连接过去还是能访问驱动器。

**Comment by apexliu** [comment]
界面上有设置参数的地方，不过核心服务还没有进行判断，等正式版本吧。

**Comment by apexliu** [comment]
已修正：8de120ba927ab783f44da1a892e0c1164e8e6e7d
