### ISSUE TITLE
账号锁定状态错误

### ISSUE THREAD

**Issue by ouchao** [eomsoft/teleport#56]
账号登录密码错误过多自动锁后，账号实际上已经自动解锁了，但上【用户】->【用户管理】->【状态】还是显示为【临时锁定】

**Comment by apexliu** [comment]
自动解锁状态实际上是在此用户再次登录时判断并改变状态的，因此，只要此用户不再次登录，此状态就不会自动改为“正常”。
新版本会在一个后台定时任务中检查，并更新自动解锁了的用户的状态。

**Comment by apexliu** [comment]
已修正，参见 5af312cb1653edf2413f20cbded10a002de73f3d
