### ISSUE TITLE
RDP录像回放，点击播放，TP助手出现崩溃

### ISSUE THREAD

**Issue by djy1121** [eomsoft/teleport#60]
win10和win7系统，Firefox浏览器，teleport原始部署，没有部署nginx，用7190端口访问，远程终端和远程桌面正常，SSH录像回放正常，RDP录像回放，点击播放就出现TP助手崩溃。
teleport版本：V3.0.0.3
TP助手版本：V3.0.0.3

**Comment by apexliu** [comment]
我自测时未能重现此问题。请确认一下是助手崩溃，还是RDP录像播放器崩溃？如果是前者，那么再次点击播放时，页面上会提示助手未运行。
另外，如果是之前的版本（v3.0.0.2）使用mstsc客户端进行远程连接记录的录像，那么RDP录像播放器是会崩溃的，所以新版本已经临时将mstsc客户端屏蔽了。

**Comment by djy1121** [comment]
之前描述有问题，应该是RDP录像播放器崩溃。
我今天将server和助手都升级到3.0.0.4版本，问题没有了

**Comment by djy1121** [comment]
之前描述有问题，应该是RDP录像播放器崩溃。
我今天将server和助手都升级到3.0.0.4版本，问题没有了
