### ISSUE TITLE
2.2.10 版本可以直接升级 v3 技术预览版吗

### ISSUE THREAD

**Issue by flapjackegg** [eomsoft/teleport#67]
如题，我看数据库的表都不太一样了，是不是只能用导出 Excel 的方式备份，再恢复呢？

**Comment by apexliu** [comment]
是的，数据库表变化非常巨大，无法直接升级到v3版，很抱歉。
而且注意，v3版的批量导入的文件格式也有调整，目前只能手工编辑再导入到v3版中。

**Comment by flapjackegg** [comment]
好的，了解
